# First stage: Build the application
FROM gradle:jdk17 as builder
LABEL author="mariaparreira"

# Define the working directory
WORKDIR /CA4/Part1/SecondVersion

# Copy the entire project into the container
COPY CA4/Part1/SecondVersion/CA2.Part1/build/libs/basic_demo-0.1.0.jar .



